version: 2

sources:
  - name: retail_raw
    tables:
      - name: orders.csv
      - name: customers.csv

models:
  - name: stg_orders
  - name: stg_customers
  - name: int_customer_orders
  - name: customer_lifetime_value
